### ISSUE TITLE
Bug report from CRAN

### ISSUE THREAD

**Issue by leeper** [leeper/csvy#23]
Please specify whether your issue is about:

 - [x] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Put your code here:

```
in function write_csvy() you have

     if (isTRUE(comment_header)) {
         m <- readLines(textConnection(y))


but you never close the connection.

Rather write:

     if (isTRUE(comment_header)) {
         con <- textConnection(y)
         on.exit(close(con))
         m <- readLines(con)
...


There may be more connections left open in other parts of the package, I 
just report the first found problem.

Please correct before 2018-08-08 to safely retain your package on CRAN.
```

**Comment by leeper** [comment]
@jonocarroll Think you could tackle this one?

**Comment by jonocarroll** [comment]
Sorry, this slipped past me (then was closed as I was writing this).

I'd like to better understand the explicit `textConnection` -- `readLines` is happy to take a string and only keep the connection open for the duration of the call. I'll look through the commit and see where this is important. 

Apologies for the delay.

**Comment by jonocarroll** [comment]
FYI, it is currently `on.exist` in 3be3643 (-> `on.exit`).

**Comment by leeper** [comment]
No worries!
