### ISSUE TITLE
Multiple tables in one file

### ISSUE THREAD

**Issue by sjackman** [leeper/csvy#5]
To keep the metadata and the data together in one file so that they don't get separated, I'd like to keep multiple tables in one TSV file. See an example below. The function `read_csvy_tables` would return a file and return a list of data frames. How do you feel about this feature, and is it something you'd be interested in implementing, or would you accept a pull request?

Background: Over at https://github.com/jennybc/sanesheets/issues/3 we're discussing a tidy file format that provides some of the benefits of a spreadsheet without all the ick of a spreadsheet. For one, we'd like a plain text file format. One of the nice features of a spreadsheet is the ability to keep multiple related sheets in one file.

### sanesheet.tsvy

```
---
name: sheet1
---
A	B
1	X
2	Y

---
name: sheet2
---
C	D	E
3	4	5
```

**Comment by sjackman** [comment]
cc @jennybc

**Comment by leeper** [comment]
I'd be open to a pull request.

**Comment by sjackman** [comment]
I don't have time in the near feature to implement this feature, so I'll close this issue. Thanks for your response, Thomas.
