### ISSUE TITLE
Tabs / TSVY?

### ISSUE THREAD

**Issue by jeremydouglass** [leeper/csvy#7]
One feature of the CSV ecosystem is the use of either tabs (TSV files) or, alternately, the ability to specify an arbitrary custom delimiter.

Could you see any affordances for TSV files in CSVY -- i.e. extending the specification ("or YAML+TSV") and perhaps extending toolchains to deal with that case?

**Comment by leeper** [comment]
This should already be supported using the `sep` argument in `read_csvy()` and `write_csvy()`.

**Comment by leeper** [comment]
Subsume into #14
